version: '3'

services:
  web:
    build: ./budget_app
    command: sh -c "/app/wait-for-it.sh db:3306 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./budget_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=budget_db
      - DB_USER=your_mysql_user
      - DB_PASSWORD=your_password
      - DB_HOST=db
      - DB_PORT=3306
      - ALLOWED_HOSTS=localhost,127.0.0.1,web

  frontend:
    build:
      context: ./budget-frontend
    volumes:
      - ./budget-frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - web

  frontend-test:
    build:
      context: ./budget-frontend
    environment:
      - CI=true
    volumes:
      - ./budget-frontend:/app
    command: npm test -- --watchAll=false --verbose

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: budget_db
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_password

volumes:
  mysql_data:
