apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  selector:
    matchLabels:
      app: react
  replicas: 1
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: budget-frontend:latest  # Use the local image name
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: react
  type: NodePort
